API_TOKEN ="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"
STTAPI_URL="https://api-inference.huggingface.co/models/oyqiz/uzbek_stt"
API_URL="https://api-inference.huggingface.co/models/shohabbosdev/text-to-audio"
API_URL_HAND="https://api-inference.huggingface.co/models/microsoft/trocr-large-handwritten"
OCR_QUOTE_API = "7uxn7fSWBW67qNckAptg2Q==5Bwp5rgj2rRZzmDN"
OCR_URL = "https://api.api-ninjas.com/v1/imagetotext"
QUOTE_URL = "https://api.api-ninjas.com/v1/quotes?category="