API_TOKEN ="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"
STTAPI_URL="https://api-inference.huggingface.co/models/oyqiz/uzbek_stt"
API_URL="https://api-inference.huggingface.co/models/shohabbosdev/text-to-audio"
API_URL_HAND="https://api-inference.huggingface.co/models/microsoft/trocr-large-handwritten"
OCR_QUOTE_API = "7uxn7fSWBW67qNckAptg2Q==5Bwp5rgj2rRZzmDN"
OCR_URL = "https://api.api-ninjas.com/v1/imagetotext"
QUOTE_URL = "https://api.api-ninjas.com/v1/quotes?category="
FACTS_URL = "https://api.api-ninjas.com/v1/facts"
apiKey = "AIzaSyA7QlweckAV7vf3hqMNdMWeWFy25xORaA4"
authDomain = "btarjimon-364d9.firebaseapp.com"
databaseURL = "https://btarjimon-364d9-default-rtdb.firebaseio.com/"
projectId = "btarjimon-364d9"
storageBucket = "btarjimon-364d9.firebasestorage.app"
messagingSenderId = "998797421280"
appId = "1:998797421280:web:4f8d8ec5ce508388acfe85"
measurementId = "G-3VSY64CFHD"
OAPI_URL = "https://oyqiz.airi.uz/api/v1/tts/"
