API_TOKEN="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"
STTAPI_URL = "https://api-inference.huggingface.co/models/oyqiz/uzbek_stt"
API_URL = "https://api-inference.huggingface.co/models/shohabbosdev/text-to-audio"
HUG_TOKEN = "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"