API_TOKEN ="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"
STTAPI_URL="https://api-inference.huggingface.co/models/oyqiz/uzbek_stt"
API_URL="https://api-inference.huggingface.co/models/shohabbosdev/text-to-audio"